### ISSUE TITLE
Tab not working properly for entering new fields

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/id.webmaker.org#180] opened 2015-04-08 19:24 UTC
Testing login in Firefox - #11 

When I enter data in the name field and hit the tab button - the next field (email) is highlighted however I have to click in it in order to enter data. Any way for it to automatically let me start entering info?

**Comment by secretrobotron** [comment] 2015-04-08 19:34
Dupe of #179.
Thanks @ldecoursy !

**Closed by secretrobotron** 2015-04-08 19:34 UTC
