### ISSUE TITLE
Password validation doesn't tell you what is required for a valid password

### ISSUE THREAD

**Issue by adamlofting** [mozilla/id.webmaker.org#173] opened 2015-04-08 10:37 UTC
![screenshot 2015-04-08 11 36 03](https://cloud.githubusercontent.com/assets/1901816/7043705/95d218e6-dde3-11e4-8ca4-39c1e8213f6f.png)

**Comment by secretrobotron** [comment] 2015-04-08 19:59
Dupe of #181.

**Closed by secretrobotron** 2015-04-08 19:59 UTC
