### ISSUE TITLE
Add messaging or redirect to the root URL `id.webmaker.org/`

### ISSUE THREAD

**Issue by adamlofting** [mozilla/id.webmaker.org#172] opened 2015-04-08 10:33 UTC
Rather than:
![screenshot 2015-04-08 11 32 28](https://cloud.githubusercontent.com/assets/1901816/7043621/f7a22d32-dde2-11e4-9eaa-67cc5ea981a6.png)

**Comment by secretrobotron** [comment] 2015-04-08 19:59
Dupe of #177.

**Closed by secretrobotron** 2015-04-08 19:59 UTC
